CREATE OR REPLACE FUNCTION sp_create_item_backuptables(varchar)
RETURNS void AS
$$
BEGIN
	execute	'CREATE TABLE ' || 'backup_tb_character_items' || '_' || $1 || '(
  dwcharid integer NOT NULL,
  wpos smallint NOT NULL,
  serial bigint NOT NULL DEFAULT 0,
  dwid integer NOT NULL DEFAULT 0,
  bygrade smallint NOT NULL DEFAULT 0,
  byrarity smallint NOT NULL DEFAULT 0,
  wcount smallint NOT NULL DEFAULT 0,
  bydeity0 smallint NOT NULL DEFAULT 0,
  bydeity1 smallint NOT NULL DEFAULT 0,
  bydeity2 smallint NOT NULL DEFAULT 0,
  bydeity3 smallint NOT NULL DEFAULT 0,
  bydeity4 smallint NOT NULL DEFAULT 0,
  bydeity5 smallint NOT NULL DEFAULT 0,
  bydeity6 smallint NOT NULL DEFAULT 0,
  bydeity7 smallint NOT NULL DEFAULT 0,
  bydeity8 smallint NOT NULL DEFAULT 0,
  bydeity9 smallint NOT NULL DEFAULT 0,
  bydeity10 smallint NOT NULL DEFAULT 0,
  bydeity11 smallint NOT NULL DEFAULT 0,
  bydeity12 smallint NOT NULL DEFAULT 0,
  bydeity13 smallint NOT NULL DEFAULT 0,
  bydeity14 smallint NOT NULL DEFAULT 0,
  bydeity15 smallint NOT NULL DEFAULT 0,
  bydeity16 smallint NOT NULL DEFAULT 0,
  bydeity17 smallint NOT NULL DEFAULT 0,
  bydeity18 smallint NOT NULL DEFAULT 0,
  bydeity19 smallint NOT NULL DEFAULT 0,
  bydeity20 smallint NOT NULL DEFAULT 0,
  bydeity21 smallint NOT NULL DEFAULT 0,
  bydeity22 smallint NOT NULL DEFAULT 0,
  bydeity23 smallint NOT NULL DEFAULT 0,
  bydeity24 smallint NOT NULL DEFAULT 0,
  bydeity25 smallint NOT NULL DEFAULT 0,
  bydeity26 smallint NOT NULL DEFAULT 0,
  bydeity27 smallint NOT NULL DEFAULT 0,
  bydeity28 smallint NOT NULL DEFAULT 0,
  bydeity29 smallint NOT NULL DEFAULT 0,
  dwchangedress integer NOT NULL DEFAULT 0
) WITH ( OIDS=TRUE )';

    execute	'CREATE TABLE ' || 'backup_tb_character_cash_items' || '_' || $1 || '(
  dwcharid integer NOT NULL,
  wpos smallint NOT NULL,
  serial bigint NOT NULL DEFAULT 0,
  dwid integer NOT NULL DEFAULT 0,
  bygrade smallint NOT NULL DEFAULT 0,
  byrarity smallint NOT NULL DEFAULT 0,
  wcount smallint NOT NULL DEFAULT 0,
  bydeity0 smallint NOT NULL DEFAULT 0,
  bydeity1 smallint NOT NULL DEFAULT 0,
  bydeity2 smallint NOT NULL DEFAULT 0,
  bydeity3 smallint NOT NULL DEFAULT 0,
  bydeity4 smallint NOT NULL DEFAULT 0,
  bydeity5 smallint NOT NULL DEFAULT 0,
  bydeity6 smallint NOT NULL DEFAULT 0,
  bydeity7 smallint NOT NULL DEFAULT 0,
  bydeity8 smallint NOT NULL DEFAULT 0,
  bydeity9 smallint NOT NULL DEFAULT 0,
  bydeity10 smallint NOT NULL DEFAULT 0,
  bydeity11 smallint NOT NULL DEFAULT 0,
  bydeity12 smallint NOT NULL DEFAULT 0,
  bydeity13 smallint NOT NULL DEFAULT 0,
  bydeity14 smallint NOT NULL DEFAULT 0,
  bydeity15 smallint NOT NULL DEFAULT 0,
  bydeity16 smallint NOT NULL DEFAULT 0,
  bydeity17 smallint NOT NULL DEFAULT 0,
  bydeity18 smallint NOT NULL DEFAULT 0,
  bydeity19 smallint NOT NULL DEFAULT 0,
  bydeity20 smallint NOT NULL DEFAULT 0,
  bydeity21 smallint NOT NULL DEFAULT 0,
  bydeity22 smallint NOT NULL DEFAULT 0,
  bydeity23 smallint NOT NULL DEFAULT 0,
  bydeity24 smallint NOT NULL DEFAULT 0,
  bydeity25 smallint NOT NULL DEFAULT 0,
  bydeity26 smallint NOT NULL DEFAULT 0,
  bydeity27 smallint NOT NULL DEFAULT 0,
  bydeity28 smallint NOT NULL DEFAULT 0,
  bydeity29 smallint NOT NULL DEFAULT 0,
  dwchangedress integer NOT NULL DEFAULT 0
) WITH ( OIDS=TRUE )';

    execute	'CREATE TABLE ' || 'backup_tb_character_store' || '_' || $1 || '(
  szaccount character varying(20) NOT NULL,
  wpos smallint NOT NULL,
  serial bigint NOT NULL DEFAULT 0,
  dwid integer NOT NULL DEFAULT 0,
  bygrade smallint NOT NULL DEFAULT 0,
  byrarity smallint NOT NULL DEFAULT 0,
  wcount smallint NOT NULL DEFAULT 0,
  bydeity0 smallint NOT NULL DEFAULT 0,
  bydeity1 smallint NOT NULL DEFAULT 0,
  bydeity2 smallint NOT NULL DEFAULT 0,
  bydeity3 smallint NOT NULL DEFAULT 0,
  bydeity4 smallint NOT NULL DEFAULT 0,
  bydeity5 smallint NOT NULL DEFAULT 0,
  bydeity6 smallint NOT NULL DEFAULT 0,
  bydeity7 smallint NOT NULL DEFAULT 0,
  bydeity8 smallint NOT NULL DEFAULT 0,
  bydeity9 smallint NOT NULL DEFAULT 0,
  bydeity10 smallint NOT NULL DEFAULT 0,
  bydeity11 smallint NOT NULL DEFAULT 0,
  bydeity12 smallint NOT NULL DEFAULT 0,
  bydeity13 smallint NOT NULL DEFAULT 0,
  bydeity14 smallint NOT NULL DEFAULT 0,
  bydeity15 smallint NOT NULL DEFAULT 0,
  bydeity16 smallint NOT NULL DEFAULT 0,
  bydeity17 smallint NOT NULL DEFAULT 0,
  bydeity18 smallint NOT NULL DEFAULT 0,
  bydeity19 smallint NOT NULL DEFAULT 0,
  bydeity20 smallint NOT NULL DEFAULT 0,
  bydeity21 smallint NOT NULL DEFAULT 0,
  bydeity22 smallint NOT NULL DEFAULT 0,
  bydeity23 smallint NOT NULL DEFAULT 0,
  bydeity24 smallint NOT NULL DEFAULT 0,
  bydeity25 smallint NOT NULL DEFAULT 0,
  bydeity26 smallint NOT NULL DEFAULT 0,
  bydeity27 smallint NOT NULL DEFAULT 0,
  bydeity28 smallint NOT NULL DEFAULT 0,
  bydeity29 smallint NOT NULL DEFAULT 0,
  dwchangedress integer NOT NULL DEFAULT 0
  ) WITH ( OIDS=TRUE )';

    execute	'CREATE TABLE ' || 'backup_tb_character_store_extend' || '_' || $1 || '(
  szaccount character varying(20) NOT NULL,
  wpos smallint NOT NULL,
  serial bigint NOT NULL DEFAULT 0,
  dwid integer NOT NULL DEFAULT 0,
  bygrade smallint NOT NULL DEFAULT 0,
  byrarity smallint NOT NULL DEFAULT 0,
  wcount smallint NOT NULL DEFAULT 0,
  bydeity0 smallint NOT NULL DEFAULT 0,
  bydeity1 smallint NOT NULL DEFAULT 0,
  bydeity2 smallint NOT NULL DEFAULT 0,
  bydeity3 smallint NOT NULL DEFAULT 0,
  bydeity4 smallint NOT NULL DEFAULT 0,
  bydeity5 smallint NOT NULL DEFAULT 0,
  bydeity6 smallint NOT NULL DEFAULT 0,
  bydeity7 smallint NOT NULL DEFAULT 0,
  bydeity8 smallint NOT NULL DEFAULT 0,
  bydeity9 smallint NOT NULL DEFAULT 0,
  bydeity10 smallint NOT NULL DEFAULT 0,
  bydeity11 smallint NOT NULL DEFAULT 0,
  bydeity12 smallint NOT NULL DEFAULT 0,
  bydeity13 smallint NOT NULL DEFAULT 0,
  bydeity14 smallint NOT NULL DEFAULT 0,
  bydeity15 smallint NOT NULL DEFAULT 0,
  bydeity16 smallint NOT NULL DEFAULT 0,
  bydeity17 smallint NOT NULL DEFAULT 0,
  bydeity18 smallint NOT NULL DEFAULT 0,
  bydeity19 smallint NOT NULL DEFAULT 0,
  bydeity20 smallint NOT NULL DEFAULT 0,
  bydeity21 smallint NOT NULL DEFAULT 0,
  bydeity22 smallint NOT NULL DEFAULT 0,
  bydeity23 smallint NOT NULL DEFAULT 0,
  bydeity24 smallint NOT NULL DEFAULT 0,
  bydeity25 smallint NOT NULL DEFAULT 0,
  bydeity26 smallint NOT NULL DEFAULT 0,
  bydeity27 smallint NOT NULL DEFAULT 0,
  bydeity28 smallint NOT NULL DEFAULT 0,
  bydeity29 smallint NOT NULL DEFAULT 0,
  dwchangedress integer NOT NULL DEFAULT 0
) WITH ( OIDS=TRUE )';

    execute	'CREATE TABLE ' || 'backup_tb_consignment_expire_items' || '_' || $1 || '(
  dwauctionid integer NOT NULL,
  byflag smallint NOT NULL DEFAULT 0,
  serial bigint NOT NULL,
  dwitemid integer NOT NULL,
  szitemname character varying(50) NOT NULL,
  bytype smallint NOT NULL DEFAULT 0,
  wequippos smallint NOT NULL DEFAULT 0,
  bygrade smallint NOT NULL DEFAULT 0,
  byrarity smallint NOT NULL DEFAULT 0,
  wcount smallint NOT NULL DEFAULT 0,
  byupgrade smallint NOT NULL DEFAULT 0,
  bydeity0 smallint NOT NULL DEFAULT 0,
  bydeity1 smallint NOT NULL DEFAULT 0,
  bydeity2 smallint NOT NULL DEFAULT 0,
  bydeity3 smallint NOT NULL DEFAULT 0,
  bydeity4 smallint NOT NULL DEFAULT 0,
  bydeity5 smallint NOT NULL DEFAULT 0,
  bydeity6 smallint NOT NULL DEFAULT 0,
  bydeity7 smallint NOT NULL DEFAULT 0,
  bydeity8 smallint NOT NULL DEFAULT 0,
  bydeity9 smallint NOT NULL DEFAULT 0,
  bydeity10 smallint NOT NULL DEFAULT 0,
  bydeity11 smallint NOT NULL DEFAULT 0,
  bydeity12 smallint NOT NULL DEFAULT 0,
  bydeity13 smallint NOT NULL DEFAULT 0,
  bydeity14 smallint NOT NULL DEFAULT 0,
  bydeity15 smallint NOT NULL DEFAULT 0,
  bydeity16 smallint NOT NULL DEFAULT 0,
  bydeity17 smallint NOT NULL DEFAULT 0,
  bydeity18 smallint NOT NULL DEFAULT 0,
  bydeity19 smallint NOT NULL DEFAULT 0,
  bydeity20 smallint NOT NULL DEFAULT 0,
  bydeity21 smallint NOT NULL DEFAULT 0,
  bydeity22 smallint NOT NULL DEFAULT 0,
  bydeity23 smallint NOT NULL DEFAULT 0,
  bydeity24 smallint NOT NULL DEFAULT 0,
  bydeity25 smallint NOT NULL DEFAULT 0,
  bydeity26 smallint NOT NULL DEFAULT 0,
  bydeity27 smallint NOT NULL DEFAULT 0,
  bydeity28 smallint NOT NULL DEFAULT 0,
  bydeity29 smallint NOT NULL DEFAULT 0,
  dwchangedress integer
  ) WITH ( OIDS=FALSE )';

    execute	'CREATE TABLE ' || 'backup_tb_consignment_sale_items' || '_' || $1 || '(
  dwauctionid integer,
  byflag smallint,
  serial bigint,
  dwitemid integer,
  szitemname character varying(50),
  bytype smallint,
  wequippos smallint,
  bygrade smallint,
  byrarity smallint,
  wcount smallint,
  byupgrade smallint,
  bydeity0 smallint,
  bydeity1 smallint,
  bydeity2 smallint,
  bydeity3 smallint,
  bydeity4 smallint,
  bydeity5 smallint,
  bydeity6 smallint,
  bydeity7 smallint,
  bydeity8 smallint,
  bydeity9 smallint,
  bydeity10 smallint,
  bydeity11 smallint,
  bydeity12 smallint,
  bydeity13 smallint,
  bydeity14 smallint,
  bydeity15 smallint,
  bydeity16 smallint,
  bydeity17 smallint,
  bydeity18 smallint,
  bydeity19 smallint,
  bydeity20 smallint,
  bydeity21 smallint,
  bydeity22 smallint,
  bydeity23 smallint,
  bydeity24 smallint,
  bydeity25 smallint,
  bydeity26 smallint,
  bydeity27 smallint,
  bydeity28 smallint,
  bydeity29 smallint,
  dwchangedress integer NOT NULL DEFAULT 0,
  wmainmenu smallint DEFAULT 0,
  wsubmenu smallint DEFAULT 0,
  byreqlevel integer DEFAULT 0,
  byreqmaxlevel integer DEFAULT 0,
  byreqclass smallint DEFAULT 0
) WITH ( OIDS=FALSE )';

    execute	'CREATE TABLE ' || 'backup_tb_consignment_sell_items' || '_' || $1 || '(
  dwauctionid integer,
  byflag smallint,
  serial bigint,
  dwitemid integer,
  szitemname character varying(50),
  bytype smallint,
  wequippos smallint,
  bygrade smallint,
  byrarity smallint,
  wcount smallint,
  byupgrade smallint,
  bydeity0 smallint,
  bydeity1 smallint,
  bydeity2 smallint,
  bydeity3 smallint,
  bydeity4 smallint,
  bydeity5 smallint,
  bydeity6 smallint,
  bydeity7 smallint,
  bydeity8 smallint,
  bydeity9 smallint,
  bydeity10 smallint,
  bydeity11 smallint,
  bydeity12 smallint,
  bydeity13 smallint,
  bydeity14 smallint,
  bydeity15 smallint,
  bydeity16 smallint,
  bydeity17 smallint,
  bydeity18 smallint,
  bydeity19 smallint,
  bydeity20 smallint,
  bydeity21 smallint,
  bydeity22 smallint,
  bydeity23 smallint,
  bydeity24 smallint,
  bydeity25 smallint,
  bydeity26 smallint,
  bydeity27 smallint,
  bydeity28 smallint,
  bydeity29 smallint,
  dwchangedress integer
) WITH ( OIDS=FALSE )';

    execute	'CREATE TABLE ' || 'backup_tb_post_items' || '_' || $1 || '(
  dwpostitemid integer,
  dwpostid integer,
  serial bigint,
  dwid integer,
  bygrade smallint,
  byrarity smallint,
  wcount smallint,
  bydeity0 smallint,
  bydeity1 smallint,
  bydeity2 smallint,
  bydeity3 smallint,
  bydeity4 smallint,
  bydeity5 smallint,
  bydeity6 smallint,
  bydeity7 smallint,
  bydeity8 smallint,
  bydeity9 smallint,
  bydeity10 smallint,
  bydeity11 smallint,
  bydeity12 smallint,
  bydeity13 smallint,
  bydeity14 smallint,
  bydeity15 smallint,
  bydeity16 smallint,
  bydeity17 smallint,
  bydeity18 smallint,
  bydeity19 smallint,
  bydeity20 smallint,
  bydeity21 smallint,
  bydeity22 smallint,
  bydeity23 smallint,
  bydeity24 smallint,
  bydeity25 smallint,
  bydeity26 smallint,
  bydeity27 smallint,
  bydeity28 smallint,
  bydeity29 smallint,
  dwchangedress integer
) WITH ( OIDS=FALSE )';

    execute	'CREATE TABLE ' || 'backup_tb_character_deco_items' || '_' || $1 || '(
  dwcharid integer NOT NULL,
  wpos smallint NOT NULL,
  serial bigint NOT NULL DEFAULT 0,
  dwid integer NOT NULL DEFAULT 0,
  bygrade smallint NOT NULL DEFAULT 0,
  byrarity smallint NOT NULL DEFAULT 0,
  wcount smallint NOT NULL DEFAULT 0,
  bydeity0 smallint NOT NULL DEFAULT 0,
  bydeity1 smallint NOT NULL DEFAULT 0,
  bydeity2 smallint NOT NULL DEFAULT 0,
  bydeity3 smallint NOT NULL DEFAULT 0,
  bydeity4 smallint NOT NULL DEFAULT 0,
  bydeity5 smallint NOT NULL DEFAULT 0,
  bydeity6 smallint NOT NULL DEFAULT 0,
  bydeity7 smallint NOT NULL DEFAULT 0,
  bydeity8 smallint NOT NULL DEFAULT 0,
  bydeity9 smallint NOT NULL DEFAULT 0,
  bydeity10 smallint NOT NULL DEFAULT 0,
  bydeity11 smallint NOT NULL DEFAULT 0,
  bydeity12 smallint NOT NULL DEFAULT 0,
  bydeity13 smallint NOT NULL DEFAULT 0,
  bydeity14 smallint NOT NULL DEFAULT 0,
  bydeity15 smallint NOT NULL DEFAULT 0,
  bydeity16 smallint NOT NULL DEFAULT 0,
  bydeity17 smallint NOT NULL DEFAULT 0,
  bydeity18 smallint NOT NULL DEFAULT 0,
  bydeity19 smallint NOT NULL DEFAULT 0,
  bydeity20 smallint NOT NULL DEFAULT 0,
  bydeity21 smallint NOT NULL DEFAULT 0,
  bydeity22 smallint NOT NULL DEFAULT 0,
  bydeity23 smallint NOT NULL DEFAULT 0,
  bydeity24 smallint NOT NULL DEFAULT 0,
  bydeity25 smallint NOT NULL DEFAULT 0,
  bydeity26 smallint NOT NULL DEFAULT 0,
  bydeity27 smallint NOT NULL DEFAULT 0,
  bydeity28 smallint NOT NULL DEFAULT 0,
  bydeity29 smallint NOT NULL DEFAULT 0,
  dwchangedress integer NOT NULL DEFAULT 0
) WITH ( OIDS=TRUE )';

	execute 'ALTER TABLE ' || 'backup_tb_character_items' || '_' || $1 || ' OWNER TO "TDH_Game"';
	execute 'ALTER TABLE ' || 'backup_tb_character_cash_items' || '_' || $1 || ' OWNER TO "TDH_Game"';
	execute 'ALTER TABLE ' || 'backup_tb_character_store' || '_' || $1 || ' OWNER TO "TDH_Game"';
	execute 'ALTER TABLE ' || 'backup_tb_character_store_extend' || '_' || $1 || ' OWNER TO "TDH_Game"';
	execute 'ALTER TABLE ' || 'backup_tb_character_deco_items' || '_' || $1 || ' OWNER TO "TDH_Game"';
	execute 'ALTER TABLE ' || 'backup_tb_consignment_expire_items' || '_' || $1 || ' OWNER TO "TDH_Game"';
	execute 'ALTER TABLE ' || 'backup_tb_consignment_sale_items' || '_' || $1 || ' OWNER TO "TDH_Game"';
	execute 'ALTER TABLE ' || 'backup_tb_consignment_sell_items' || '_' || $1 || ' OWNER TO "TDH_Game"';
	execute 'ALTER TABLE ' || 'backup_tb_post_items' || '_' || $1 || ' OWNER TO "TDH_Game"';
END
$$
LANGUAGE plpgsql;
